// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbrvslkoalbwxvcmqspo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicnZzbGtvYWxid3h2Y21xc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzc3ODYsImV4cCI6MjA2OTgxMzc4Nn0.ch-GhUipe1DaOuOLYuJpyT6i7a0yaiph5EWyV1v_Ons";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});